### ISSUE TITLE
replace your.en.url to api.baobab.klaytn.net

### ISSUE THREAD

**Issue by kjhman21** [klaytn/klaytn-docs#381]
There are some urls `https://your.en.url:8651`.

This is also could be good to replace with `https://api.baobab.klaytn.net:8651` for easier to use.

https://docs.klaytn.com/dapp/sdk/caver-js/getting-started#sending-klay-at-a-glance

**Comment by terrikwak** [comment]
https://github.com/klaytn/klaytn-docs/pull/416
