### ISSUE TITLE
About mistranslation

### ISSUE THREAD

**Issue by hyunsooda** [klaytn/klaytn-docs#387]
Hi,

Crowdin seemed to translate `To the child chain, the child chain bridge operator account is used.` as `자식 체인으로 자치를 전송할때는 자식 체인 브리지 오퍼레이터 계정이 사용됩니다.` in [Value-Transfer doc](https://ko.docs.klaytn.com/node/service-chain/references/value-transfer). The word `자치` should be `가치` as appeared preceding statement, which is correct. I'm guessing this mistranslation seemed to occur by conservative context. Translation testing by Crowdin seems to be out of my authorization. If there's anyone who encountered this kind of problem, please let me know what's correct. Thank you

**Comment by terrikwak** [comment]
Hi, @hyunsooda. I apologize for the late answer 😢  If you want to participate in the translation, please follow the link: https://crowdin.com/project/klaytn-docs/invite?d=85n6j4j675t683c3h463e3t6c3q4r48383d3. Thank you so much :)
