### ISSUE TITLE
sample code typo

### ISSUE THREAD

**Issue by jhleee** [klaytn/klaytn-docs#447]
**Describe the issues and typos**
Missing comma.

**Expected behavior**
Just add comma.

**Screenshots**
![image](https://user-images.githubusercontent.com/7456523/170193667-804d6b07-aec7-4970-907b-afe38ecea821.png)

If applicable, add screenshots to help explain the reported issues.

**Comment by terrikwak** [comment]
Fixed. Thank you :)
