### ISSUE TITLE
Addition of Oracles section to the documentation. 

### ISSUE THREAD

**Issue by supra-simeon** [klaytn/klaytn-docs#534]
**Describe the content contribution you'd suggest**
Hey everyone, I'd like to add a content-contribution request for the addition of an oracle section in: **_Klaytn docs > dApp Developers_** > **Oracles**

**Klaytn** is currently integrated with _**SupraOracles**_. This issue aims to add developer guides to demonstrate how developers on Klaytn can use: 
- SupraOracles [price feed data](https://data.supraoracles.com/networks/klaytn) for Klaytn network.
- [VRF](https://supraoracles.com/docs/vrf1/a-deeper-dive-into-supra-vrf) 

products in smart contracts on Klaytn ( testnet right now). 

**Elaborate the suggested content contribution with samples**
Here's a sample of what the Oracles section would look like: 
![Sample of Oracle section](https://user-images.githubusercontent.com/122936734/215778015-b1a9b21e-91b8-444d-8325-8fc6e8a6da87.png)

**Additional context**
Oracles are a core part of building powerful smart contracts since they bring off-chain data/computations onchain. SupraOracles is integrated has Klaytn and it would be beneficial to Klaytn ecosystem projects if the guides are tailored specifically for Klaytn developments are made available. Thank you :)

**Comment by praveen-klaytn** [comment]
Closing this issue as it is added to Klaytn docs https://docs.klaytn.foundation/docs/build/tools/oracles/supraoracles/.
